[package]
summary = "Library to parse the x86 CPUID instruction"
cargo-install-bin = false
cargo-toml-patch-comments = [
    "- Remove clashing binary package",
    "- Remove cli and display features",
]
supported-arches = ["x86_64", "i686"]

[features]
enable = [
    "std",
    "serialize",
]
