[package]
summary = "Library to parse the x86 CPUID instruction"
cargo-install-bin = false

[features]
hide = [
    "cli",
    "display",
]

[[package.extra-patches]]
comments = [
    "Remove termimad dependency and display feature",
]
file = "rust-raw-cpuid-11.0.2-Remove_unused_dependency.diff"
number = 10

