[package]
summary = "Statistical routines for ArrayBase"

[requires]
build = [
    "tomcli",
]

[scripts.prep]
post = [
    "# Do not depend on criterion; it is needed only for benchmarks.",
    "tomcli set Cargo.toml del dev-dependencies.criterion",
]

[[package.extra-patches]]
comments = [
    "https://github.com/rust-ndarray/ndarray-stats/issues/96",
    "Bump approx dependency",
]
file = "rust-ndarray-stats-0.5.1-Bump_approx_dependency.diff"
number = 10

[tests]
skip = [
    "entropy::tests::test_cross_entropy_with_noisy_negative_qs",
    "entropy::tests::test_kl_with_noisy_negative_qs",
]
comments = [
    "Probably using debug_assert!"
]
