[features]
enable-all = true

[package]
summary = "Statistical routines for ArrayBase"
cargo-toml-patch-comments = [
    "- Bump approx dependency",
    "  https://github.com/rust-ndarray/ndarray-stats/issues/96",
]

[requires]
build = [
    "tomcli",
]

[scripts.prep]
post = [
    "# Do not depend on criterion; it is needed only for benchmarks.",
    "tomcli set Cargo.toml del dev-dependencies.criterion",
]

[tests]
skip = [
    "entropy::tests::test_cross_entropy_with_noisy_negative_qs",
    "entropy::tests::test_kl_with_noisy_negative_qs",
]
comments = [
    "Probably using debug_assert!"
]
