[package]
summary = "Statistical routines for ArrayBase"

[requires]
build = [
    "tomcli",
]

[scripts.prep]
post = [
    "# Do not depend on criterion; it is needed only for benchmarks.",
    "tomcli set Cargo.toml del dev-dependencies.criterion",
]

[tests]
skip = [
    "entropy::tests::test_cross_entropy_with_noisy_negative_qs",
    "entropy::tests::test_kl_with_noisy_negative_qs",
]
comments = [
    "Tests only pass in debug profile because they rely on `debug_assert!` in `noisy_float`",
]
