packages:
  rust-metrics-exporter-prometheus:
    # https://github.com/metrics-rs/metrics
    paths: [ rust-metrics-exporter-prometheus ]
    specfile_path: rust-metrics-exporter-prometheus.spec
    upstream_package_name: metrics-exporter-prometheus
    downstream_package_name: rust-metrics-exporter-prometheus
    actions: &Actions-Package-no-rust2rpm
      fix-spec-file: []
      create-archive:
        - sh -c 'spectool -g -s0 ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
        - sh -c 'echo ${PACKIT_UPSTREAM_PACKAGE_NAME}-${PACKIT_PROJECT_VERSION}.crate'
      get-current-version:
        - sh -c 'rpmspec -q --qf "%{Version}" --srpm ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
  rust-metrics:
    # Updating metrics
    paths: [ rust-metrics ]
    specfile_path: rust-metrics.spec
    upstream_package_name: metrics
    downstream_package_name: rust-metrics
    actions: &Actions-Package-rust2rpm
      <<: *Actions-Package-no-rust2rpm
      fix-spec-file:
        - sh -c 'rust2rpm ${PACKIT_UPSTREAM_PACKAGE_NAME}'
  rust-metrics-util:
    # https://github.com/metrics-rs/metrics
    paths: [ rust-metrics-util ]
    specfile_path: rust-metrics-util.spec
    upstream_package_name: metrics-util
    downstream_package_name: rust-metrics-util
    actions: *Actions-Package-no-rust2rpm
  rust-mockall:
    # Additional updates
    paths: [ rust-mockall ]
    specfile_path: rust-mockall.spec
    upstream_package_name: mockall
    downstream_package_name: rust-mockall
    actions: *Actions-Package-rust2rpm
  rust-mockall_derive:
    # Additional updates
    paths: [ rust-mockall_derive ]
    specfile_path: rust-mockall_derive.spec
    upstream_package_name: mockall_derive
    downstream_package_name: rust-mockall_derive
    actions: *Actions-Package-rust2rpm
  rust-auto_enums:
    # New package
    paths: [ rust-auto_enums ]
    specfile_path: rust-auto_enums.spec
    upstream_package_name: auto_enums
    downstream_package_name: rust-auto_enums
    actions: *Actions-Package-no-rust2rpm
  rust-derive_utils:
    # New package
    paths: [ rust-derive_utils ]
    specfile_path: rust-derive_utils.spec
    upstream_package_name: derive_utils
    downstream_package_name: rust-derive_utils
    actions: *Actions-Package-rust2rpm

srpm_build_deps:
  - rust2rpm

jobs:
  - job: copr_build
    trigger: commit
    update_release: false
    owner: lecris
    project: rust-metrics
    targets:
      - fedora-rawhide
