packages:
  rust-metrics:
    # https://github.com/metrics-rs/metrics
    paths: [ rust-metrics ]
    specfile_path: rust-metrics.spec
    upstream_package_name: metrics
    downstream_package_name: rust-metrics
    actions: &Actions-Package-rust2rpm
      fix-spec-file:
        - sh -c 'rust2rpm ${PACKIT_UPSTREAM_PACKAGE_NAME}'
      create-archive:
        - sh -c 'spectool -g -s0 ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
        - sh -c 'echo ${PACKIT_UPSTREAM_PACKAGE_NAME}-${PACKIT_PROJECT_VERSION}.crate'
      get-current-version:
        - sh -c 'rpmspec -q --qf "%{Version}" --srpm ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
  rust-metrics-exporter-prometheus:
    # https://github.com/metrics-rs/metrics
    paths: [ rust-metrics-exporter-prometheus ]
    specfile_path: rust-metrics-exporter-prometheus.spec
    upstream_package_name: metrics-exporter-prometheus
    downstream_package_name: rust-metrics-exporter-prometheus
    actions: *Actions-Package-rust2rpm
  rust-metrics-util:
    # https://github.com/metrics-rs/metrics
    paths: [ rust-metrics-util ]
    specfile_path: rust-metrics-util.spec
    upstream_package_name: metrics-util
    downstream_package_name: rust-metrics-util
    actions: &Actions-Package-no-rust2rpm
      <<: *Actions-Package-rust2rpm
      fix-spec-file: []

  ## Dependencies
  rust-quanta:
    # https://github.com/metrics-rs/quanta
    paths: [ rust-quanta ]
    specfile_path: rust-quanta.spec
    upstream_package_name: quanta
    downstream_package_name: rust-quanta
    actions: *Actions-Package-no-rust2rpm
  rust-average:
    # https://github.com/vks/average
    paths: [ rust-average ]
    specfile_path: rust-average.spec
    upstream_package_name: average
    downstream_package_name: rust-average
    actions: *Actions-Package-no-rust2rpm
  rust-raw-cpuid:
    # https://github.com/gz/rust-cpuid
    paths: [ rust-raw-cpuid ]
    specfile_path: rust-raw-cpuid.spec
    upstream_package_name: raw-cpuid
    downstream_package_name: rust-raw-cpuid
    actions: *Actions-Package-no-rust2rpm
  rust-ndarray:
    # https://github.com/rust-ndarray/ndarray
    paths: [ rust-ndarray ]
    specfile_path: rust-ndarray.spec
    upstream_package_name: ndarray
    downstream_package_name: rust-ndarray
    actions: *Actions-Package-no-rust2rpm
  rust-ndarray-stats:
    # https://github.com/rust-ndarray/ndarray-stats
    paths: [ rust-ndarray-stats ]
    specfile_path: rust-ndarray-stats.spec
    upstream_package_name: ndarray-stats
    downstream_package_name: rust-ndarray-stats
    actions: *Actions-Package-no-rust2rpm
  rust-ndarray-rand:
    # https://github.com/rust-ndarray/ndarray
    paths: [ rust-ndarray-rand ]
    specfile_path: rust-ndarray-rand.spec
    upstream_package_name: ndarray-rand
    downstream_package_name: rust-ndarray-rand
    actions: *Actions-Package-rust2rpm
  rust-sketches-ddsketch:
    # https://github.com/mheffner/rust-sketches-ddsketch
    paths: [ rust-sketches-ddsketch ]
    specfile_path: rust-sketches-ddsketch.spec
    upstream_package_name: sketches-ddsketch
    downstream_package_name: rust-sketches-ddsketch
    actions: *Actions-Package-rust2rpm
  rust-defmac:
    # https://github.com/bluss/defmac
    paths: [ rust-defmac ]
    specfile_path: rust-defmac.spec
    upstream_package_name: defmac
    downstream_package_name: rust-defmac
    actions: *Actions-Package-rust2rpm
  rust-core_affinity:
    # https://github.com/Elzair/core_affinity_rs
    paths: [ rust-core_affinity ]
    specfile_path: rust-core_affinity.spec
    upstream_package_name: core_affinity
    downstream_package_name: rust-core_affinity
    actions: *Actions-Package-rust2rpm

  # Waiting to be updated
  rust-ordered-float:
    paths: [ rust-ordered-float ]
    specfile_path: rust-ordered-float.spec
    upstream_package_name: ordered-float
    downstream_package_name: rust-ordered-float
    actions: *Actions-Package-rust2rpm

srpm_build_deps:
  - rust2rpm

jobs:
  - job: copr_build
    trigger: commit
    update_release: false
    targets:
      - fedora-rawhide
