[package]
cargo-toml-patch-comments = [
    "Remove oper test: Uses workspace-only crate ndarray-gen",
]

[features]
enable = [
    "default",
    "serde",
    "test",
    "std",
    "rayon",
    "matrixmultiply-threading",
    "portable-atomic-critical-section",
]
hide = [
    "blas",
    "docs",
    "serde-1",
]
