[package]
cargo-toml-patch-comments = [
    "- Bump approx dependency",
    "  https://github.com/rust-ndarray/ndarray/pull/1380",
]

[features]
enable = [
    "default",
    "serde",
    "test",
    "rayon",
    "matrixmultiply-threading",
]
hide = [
    "blas",
    "cblas-sys",
    "docs",
    "serde-1",
    "approx-0_5",
]
