[requires]
build = [
    "tomcli",
]

[scripts.prep]
post = [
    "# Do not depend on criterion; it is needed only for benchmarks.",
    "tomcli set Cargo.toml del dev-dependencies.criterion",
]

[package]
cargo-toml-patch-comments = [
    "- Bump average dependency",
]

[tests]
skip = [
    "instant::tests::test_recent",
]
comments = [
    "Flaky test"
]
