[features]
enable = [
    "default",
    "prost",
]

[requires]
build = [
    "tomcli",
]

[scripts.prep]
post = [
    "# Do not depend on criterion; it is needed only for benchmarks.",
    "tomcli set Cargo.toml del dev-dependencies.criterion",
]

[package]
cargo-toml-patch-comments = [
    "- Bump average dependency",
    "- Bump prost-types dependency",
    "- Remove flaky_tests from default feature",
]

[tests]
skip = [
    "instant::tests::test_recent",
]
comments = [
    "More flaky tests"
]
