[features]
enable-all = true

[requires]
build = [
    "tomcli",
]

[scripts.prep]
post = [
    "# Do not depend on criterion; it is needed only for benchmarks.",
    "tomcli set Cargo.toml del dev-dependencies.criterion",
]

[package]
cargo-toml-patch-comments = [
    "- Relax predicates dependencies",
    "- Bump sketches-ddsketch dependency",
    "- Bump ndarray dependency",
]

