[features]
enable-all = true

[requires]
build = [
    "tomcli",
]

[scripts.prep]
post = [
    "# Do not depend on criterion; it is needed only for benchmarks.",
    "tomcli set Cargo.toml del dev-dependencies.criterion",
]

[package]
cargo-toml-patch-comments = [
    "- Relax predicates dependencies",
    "- Widen mockall dependency",
    "  (see https://github.com/metrics-rs/metrics/pull/499)",
]

